package net.dunice.mk.rsmtelegrambot.constant;

public class ButtonName {
    public static final String
        UPDATE_PROFILE = "⚙ Изменить профиль",
        YES = "Да",
        NO = "Нет",
        OK = "Ок",
        GRANT_ADMIN = "\uD83C\uDD99 Назначить админом",
        REVOKE_ADMIN = "⛔\uFE0F Отстранить админа",
        ADMINS_LIST = "☰ Список админов",
        BAN = "❌ Забанить",
        UNBAN = "✅ Разбанить",
        DELETE_USER = "\uD83D\uDEB7 Удалить пользователя",
        ADD_EVENT = "\uD83D\uDDD3 Добавить мероприятие",
        ADD_STOCK = "\uD83D\uDDD3 Добавить акцию",
        TO_MAIN_MENU = "⌂ В главное меню",
        EVENTS_LIST = "☰ Мероприятия",
        STOCKS_LIST = "☰ Акции",
        PARTNERS_LIST = "☰ Партнеры",
        USERS_LIST = "☰ Пользователи",
        TRY_AGAIN = "\uD83D\uDD01 Попробовать eще раз",
        RSM_MEMBER = "Член РСМ",
        RSM_PARTNER = "Партнер РСМ",
        SKIP = "⏭\uFE0F Пропустить",
        CANCEL = "❌ Отмена",
        CANCEL_CHANGES = "❌ Отменить изменения",
        DELETE_EVENT = "\uD83D\uDDD1 Удалить мероприятие",
        CHANGE_DISCOUNT = "✏\uFE0F Изменить скидку",
        EDIT_EVENT = "✏\uFE0F Редактировать мероприятие",
        PREVIOUS_PAGE = "⬅",
        NEXT_PAGE = "➡",
        SEND_MESSAGE_TO_EVERYONE = "✉ Сообщение всем",
        PERIOD_ANALYTICS = "\uD83D\uDCC8 Аналитика за период",
        ACTIVATE_PARTNER = "✅ Активировать партнера",
        DEACTIVATE_PARTNER = "⛔\uFE0F Деактивировать партнера",
        CONFIRM = "✅ Подтвердить",
        CONFIRM_CHANGES = "✅ Подтвердить изменения",
        REJECT = "❌ Отказать",
        GET_DISCOUNT_CODE = "\uD83D\uDD11 Получить код скидки",
        VERIFICATION_CODE = "\uD83D\uDD11 Проверочный код",
        UPDATE_DISCOUNT_CODE = "\uD83D\uDCCC Обновить код",
        NEW_CHECK = "\uD83E\uDDFE Сформировать чек",
        CHANGE_LOGO = "Изменить логотип",
        CHANGE_NAME = "Изменить название",
        CHANGE_CATEGORY = "Изменить категорию",
        CHANGE_INFO = "Изменить описание",
        CHANGE_PHONE_NUMBER = "Изменить номер телефона",
        CHANGE_ADDRESS = "Изменить адрес",
        CHANGE_PERIOD_START = "Изменить начало",
        CHANGE_PERIOD_END = "Изменить окончание",
        DELETE_STOCK = "Удалить акцию",
        EDIT_STOCK = "Редактировать акцию";
}
