package net.dunice.mk.rsmtelegrambot.constant;

public class ButtonName {
    public static final String
        UPDATE_PROFILE = "⚙ Изменить профиль",
        YES = "Да",
        NO = "Нет",
        GRANT_ADMIN = "Назначить админом",
        REVOKE_ADMIN = "Отстранить админа",
        ADMINS_LIST = "☰ Список админов",
        BAN = "Забанить",
        UNBAN = "Разбанить",
        DELETE_USER = "Удалить пользователя",
        ADD_EVENT = "Добавить мероприятие",
        TO_MAIN_MENU = "⌂ В главное меню",
        EVENTS_LIST = "☰ Мероприятия",
        PARTNERS_LIST = "☰ Партнеры",
        USERS_LIST = "☰ Пользователи",
        TRY_AGAIN = "\uD83D\uDD01 Попробовать eще раз",
        RSM_MEMBER = "Член РСМ",
        RSM_PARTNER = "Партнер РСМ",
        CANCEL = "❌ Отмена",
        DELETE_EVENT = "Удалить мероприятие",
        CHANGE_DISCOUNT = "Изменить скидку",
        EDIT_EVENT = "Редактировать мероприятие",
        PREVIOUS_PAGE = "⬅ Предыдущая страница",
        NEXT_PAGE = "Следующая страница ➡",
        SEND_MESSAGE_TO_EVERYONE = "✉ Сообщение всем",
        PERIOD_ANALYTICS = "Аналитика за период",
        ACTIVATE_PARTNER = "Активировать партнера",
        DEACTIVATE_PARTNER = "Деактивировать партнера",
        CONFIRM = "✅Подтвердить",
        REJECT = "❎Отказать",
        GET_DISCOUNT_CODE = "Получить код скидки",
        VERIFICATION_CODE = "Проверочный код",
        UPDATE_DISCOUNT_CODE = "Обновить код";
}
