package net.dunice.mk.rsmtelegrambot.constant;

public enum Menu {
    SELECTION_MENU,
    SELECTION_USER_TYPE_MENU,
    MAIN_MENU,
    ADMIN_MAIN_MENU,
    PARTNER_MAIN_MENU,
    SUPERUSER_MAIN_MENU,
    GO_TO_MAIN_MENU,
    TRY_AGAIN_MENU,
    TRY_AGAIN_OR_GO_TO_MAIN_MENU,
    CANCEL_MENU,
    CATEGORY_MENU,
    EVENT_FIELDS_MENU,
    BROADCAST_MESSAGE_MENU
}
