version: '3'

services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rsm_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres789456
      - BOT_NAME=bot
      - BOT_TOKEN=7274628225:AAGukzY_RtjzxD2n1yIQMATX3IsUvv9W5v4

  db:
    image: 'postgres:15-alpine'
    restart: always
    volumes:
      - pgdata5:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres789456
      - POSTGRES_DB=rsm_db
    ports:
      - 5432:5432
volumes:
  pgdata5:
    name: postgres-volume