jpa:
  generate-ddl: true
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      format_sql: true
  show-sql: true

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  enabled: true

web:
  resources:
    add-mappings: false

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        type: trace

spring:
  application:
    name: rsm-telegram-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/rsm_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
