CREATE TABLE category
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE partners
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    phone            VARCHAR(255)                            NOT NULL,
    discount_percent INTEGER                                 NOT NULL,
    category_id      BIGINT                                  NOT NULL,
    logo             VARCHAR(255)                            NOT NULL,
    partners_info    VARCHAR(255)                            NOT NULL,
    discount_date    DATE                                    NOT NULL,
    CONSTRAINT pk_partners PRIMARY KEY (id),
    CONSTRAINT uc_partners_name UNIQUE (name),
    CONSTRAINT uc_partners_phone UNIQUE (phone),
    CONSTRAINT fk_partners_on_category FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE users
(
    tg_id        BIGINT                      NOT NULL,
    full_name    VARCHAR(255)                NOT NULL,
    phone_number VARCHAR(255)                NOT NULL,
    user_role    VARCHAR(255)                NOT NULL,
    birth_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    first_name   VARCHAR(255)                NOT NULL,
    info         VARCHAR(255)                NOT NULL,
    user_card    VARCHAR(255)                NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (tg_id),
    CONSTRAINT uc_users_full_name UNIQUE (full_name),
    CONSTRAINT uc_users_phone_number UNIQUE (phone_number),
    CONSTRAINT uc_users_user_card UNIQUE (user_card)
);

CREATE TABLE checks
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    partner_id       BIGINT                                  NOT NULL,
    check_sum        DOUBLE PRECISION                        NOT NULL,
    discount_percent INTEGER                                 NOT NULL,
    user_card        BIGINT                                  NOT NULL,
    date             DATE                                    NOT NULL,
    CONSTRAINT pk_checks PRIMARY KEY (id),
    CONSTRAINT fk_checks_on_partner FOREIGN KEY (partner_id) REFERENCES partners (id),
    CONSTRAINT fk_checks_on_user_card FOREIGN KEY (user_card) REFERENCES users (tg_id)
);

CREATE TABLE events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    event_date  DATE                                    NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    link        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);