ALTER TABLE stocks
    DROP CONSTRAINT IF EXISTS fk_stocks_partners;
ALTER TABLE stocks
    DROP CONSTRAINT IF EXISTS pk_stocks CASCADE;
ALTER TABLE stocks
    DROP COLUMN stocks_id;

ALTER TABLE stocks
    ADD COLUMN stocks_id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE stocks
    ADD CONSTRAINT pk_stocks PRIMARY KEY (stocks_id);
ALTER TABLE stocks
    ADD CONSTRAINT fk_stocks_partners FOREIGN KEY (partner_tg_id) REFERENCES partners (partner_tg_id)