name: Deploy-action

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project from repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          architecture: x64

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew clean build

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files via rsync
        run: |
          rsync -av --delete /home/runner/work/rsm-telegram-bot/rsm-telegram-bot/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/user/rsm-telegram-bot/

      - name: Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'bash -s' << 'ENDSSH'
          cd /home/user/rsm-telegram-bot
          docker-compose down
          docker image prune -a -f
          docker-compose build --no-cache
          docker-compose up -d
          docker builder prune -f
          ENDSSH
